"""Live API clients and parsers for OpenHeat v0.6.3.

Operational changes from v0.6:
- Use Open-Meteo without API key and explicitly request Asia/Singapore timezone.
- Use legacy data.gov.sg /v1/environment endpoints by default; v2 remains optional.
- Treat DATA_GOV_SG_API_KEY as optional future-proofing, not a prerequisite.
- Parse both v1 and v2 NEA schemas, including station-list changes, null values, and the current WBGT records/item/readings shape.
- Store fetch timestamps and endpoint metadata for archive/debugging.
"""
from __future__ import annotations

from dataclasses import dataclass
import math
import os
import time
from typing import Any, Dict, Optional, Sequence

import pandas as pd
import requests

from .time_utils import to_singapore_time_series, utc_now_iso

OPENMETEO_FORECAST_URL = "https://api.open-meteo.com/v1/forecast"
DATAGOV_V1_ENVIRONMENT_BASE = "https://api.data.gov.sg/v1/environment"
DATAGOV_V2_REALTIME_BASE = "https://api-open.data.gov.sg/v2/real-time/api"

NEA_V1_API_ENDPOINTS = {
    "air_temperature": "air-temperature",
    "relative_humidity": "relative-humidity",
    "wind_speed": "wind-speed",
    "wind_direction": "wind-direction",
    "rainfall": "rainfall",
    "wbgt": "wbgt",
}
NEA_V2_API_ENDPOINTS = {
    "air_temperature": "air-temperature",
    "relative_humidity": "relative-humidity",
    "wind_speed": "wind-speed",
    "wind_direction": "wind-direction",
    "rainfall": "rainfall",
    "wbgt": "weather",
}


@dataclass(frozen=True)
class Location:
    lat: float
    lon: float
    name: str = "location"


def _request_json(
    url: str,
    params: Optional[dict] = None,
    timeout: int = 30,
    api_key: Optional[str] = None,
    max_retries: int = 2,
    backoff_seconds: float = 2.0,
) -> Dict[str, Any] | list[Dict[str, Any]]:
    """GET JSON with light retry behaviour and optional API key header."""
    headers = {"User-Agent": "OpenHeat-ToaPayoh/0.6.1 academic-prototype"}
    key = api_key or os.getenv("DATA_GOV_SG_API_KEY")
    if key:
        headers["x-api-key"] = key

    last_exc: Exception | None = None
    for attempt in range(max_retries + 1):
        try:
            r = requests.get(url, params=params, timeout=timeout, headers=headers)
            if r.status_code == 429 and attempt < max_retries:
                time.sleep(backoff_seconds * (attempt + 1))
                continue
            r.raise_for_status()
            payload = r.json()
            if isinstance(payload, dict):
                payload.setdefault("_openheat_fetch_timestamp_utc", utc_now_iso())
                payload.setdefault("_openheat_endpoint_url", r.url)
            return payload
        except Exception as exc:  # pragma: no cover - network behaviour
            last_exc = exc
            if attempt < max_retries:
                time.sleep(backoff_seconds * (attempt + 1))
                continue
            raise
    raise RuntimeError(f"Request failed without exception object: {url}") from last_exc


def _ensure_openmeteo_hourly_payload(payload: Dict[str, Any] | list[Dict[str, Any]]) -> list[Dict[str, Any]]:
    if isinstance(payload, list):
        return payload
    if isinstance(payload, dict) and "hourly" in payload:
        return [payload]
    raise ValueError("Open-Meteo returned an unexpected payload shape.")


def _openmeteo_hourly_to_frame(payload: Dict[str, Any], *, location_id: str | None = None) -> pd.DataFrame:
    hourly = payload.get("hourly", {}) or {}
    df = pd.DataFrame(hourly)
    if df.empty:
        raise ValueError("Open-Meteo returned no hourly data.")
    if "time" in df.columns:
        df["time"] = to_singapore_time_series(df["time"])
    if "wind_speed_10m" in df.columns:
        df["wind_speed_10m_ms"] = pd.to_numeric(df["wind_speed_10m"], errors="coerce")
    df["source"] = "open-meteo"
    df["source_lat"] = payload.get("latitude")
    df["source_lon"] = payload.get("longitude")
    df["forecast_timezone"] = "Asia/Singapore"
    df["forecast_spatial_note"] = (
        "Open-Meteo is used as neighbourhood background meteorology; "
        "intra-Toa Payoh spatial variation is generated by grid features/statistical downscaling, "
        "not by a 1-km Singapore forecast model."
    )
    if location_id is not None:
        df["location_id"] = location_id
    return df


def fetch_openmeteo_forecast(
    lat: float,
    lon: float,
    *,
    timezone: str = "Asia/Singapore",
    forecast_days: int = 4,
    timeout: int = 30,
) -> pd.DataFrame:
    """Fetch hourly background meteorology from Open-Meteo.

    wind_speed_unit=ms and timezone=Asia/Singapore are explicitly requested to
    avoid unit conversion and UTC/SGT calibration mistakes.
    """
    params = {
        "latitude": lat,
        "longitude": lon,
        "hourly": ",".join([
            "temperature_2m",
            "relative_humidity_2m",
            "wind_speed_10m",
            "shortwave_radiation",
            "direct_radiation",
            "diffuse_radiation",
            "cloud_cover",
        ]),
        "timezone": timezone,
        "forecast_days": forecast_days,
        "wind_speed_unit": "ms",
    }
    payload = _request_json(OPENMETEO_FORECAST_URL, params=params, timeout=timeout)
    return _openmeteo_hourly_to_frame(_ensure_openmeteo_hourly_payload(payload)[0], location_id="background")


def fetch_openmeteo_forecast_multi(
    locations: Sequence[Location],
    *,
    timezone: str = "Asia/Singapore",
    forecast_days: int = 4,
    timeout: int = 30,
) -> pd.DataFrame:
    """Fetch Open-Meteo for multiple locations in one call.

    This avoids for-loop rate-limit problems if a later version uses several
    background points. For Toa Payoh v0.6.1, the preferred approach remains one
    background forecast plus grid-feature downscaling.
    """
    if not locations:
        raise ValueError("locations cannot be empty")
    params = {
        "latitude": ",".join(str(x.lat) for x in locations),
        "longitude": ",".join(str(x.lon) for x in locations),
        "hourly": ",".join([
            "temperature_2m",
            "relative_humidity_2m",
            "wind_speed_10m",
            "shortwave_radiation",
            "direct_radiation",
            "diffuse_radiation",
            "cloud_cover",
        ]),
        "timezone": timezone,
        "forecast_days": forecast_days,
        "wind_speed_unit": "ms",
    }
    payload = _request_json(OPENMETEO_FORECAST_URL, params=params, timeout=timeout)
    pieces: list[pd.DataFrame] = []
    for loc, sub in zip(locations, _ensure_openmeteo_hourly_payload(payload)):
        pieces.append(_openmeteo_hourly_to_frame(sub, location_id=loc.name))
    return pd.concat(pieces, ignore_index=True)


def fetch_datagov_realtime_api(
    api: str,
    *,
    date: Optional[str] = None,
    date_time: Optional[str] = None,
    timeout: int = 30,
    api_key: Optional[str] = None,
    api_version: str = "v1",
) -> Dict[str, Any]:
    """Fetch one Singapore data.gov.sg realtime weather API.

    Default v1 endpoint examples:
    - https://api.data.gov.sg/v1/environment/wbgt
    - https://api.data.gov.sg/v1/environment/air-temperature
    - https://api.data.gov.sg/v1/environment/relative-humidity
    - https://api.data.gov.sg/v1/environment/wind-speed
    """
    if date and date_time:
        raise ValueError("Pass either date or date_time, not both.")
    if api_version not in {"v1", "v2"}:
        raise ValueError("api_version must be 'v1' or 'v2'.")
    endpoints = NEA_V1_API_ENDPOINTS if api_version == "v1" else NEA_V2_API_ENDPOINTS
    if api not in endpoints:
        raise ValueError(f"Unknown api={api!r}. Choose from {sorted(endpoints)}")

    endpoint = endpoints[api]
    if api_version == "v1":
        url = f"{DATAGOV_V1_ENVIRONMENT_BASE}/{endpoint}"
        params: dict[str, str] = {}
    else:
        url = f"{DATAGOV_V2_REALTIME_BASE}/{endpoint}"
        params = {"api": "wbgt"} if api == "wbgt" else {}
    if date:
        params["date"] = date
    if date_time:
        params["date_time"] = date_time
    payload = _request_json(url, params=params, timeout=timeout, api_key=api_key)
    if isinstance(payload, list):
        raise ValueError("data.gov.sg returned a list payload unexpectedly.")
    payload.setdefault("_openheat_api_version", api_version)
    payload.setdefault("_openheat_api_name", api)
    return payload



def _first_present(*values):
    """Return the first non-empty value while preserving 0."""
    for v in values:
        if v is not None and v != "":
            return v
    return None


def _station_meta_from_any(obj: dict[str, Any] | None, *, fallback_id: str | None = None) -> dict[str, Any]:
    """Extract station metadata from several data.gov.sg v2-style shapes.

    data.gov.sg realtime payloads are not identical across APIs. Some include a
    separate `stations` list; some embed station details inside each reading; some
    use latitude/longitude while others use lat/lng. The current WBGT v2 endpoint
    nests station id/name in `record.item.readings[].station` while coordinates
    are a sibling `record.item.readings[].location`, so this helper checks both.
    """
    obj = obj or {}
    station_obj = obj.get("station") if isinstance(obj.get("station"), dict) else obj
    if isinstance(obj.get("location"), dict):
        loc = obj.get("location", {}) or {}
    elif isinstance(station_obj.get("location"), dict):
        loc = station_obj.get("location", {}) or {}
    else:
        loc = {}
    sid = _first_present(
        station_obj.get("id"), station_obj.get("stationId"), station_obj.get("station_id"),
        obj.get("stationId"), obj.get("station_id"), obj.get("id"), fallback_id,
    )
    lat = _first_present(
        loc.get("latitude"), loc.get("lat"),
        station_obj.get("latitude"), station_obj.get("lat"),
        obj.get("latitude"), obj.get("lat"),
    )
    lon = _first_present(
        loc.get("longitude"), loc.get("lon"), loc.get("lng"),
        station_obj.get("longitude"), station_obj.get("lon"), station_obj.get("lng"),
        obj.get("longitude"), obj.get("lon"), obj.get("lng"),
    )
    return {
        "station_id": str(sid) if sid is not None else None,
        "device_id": _first_present(station_obj.get("deviceId"), station_obj.get("device_id"), obj.get("deviceId"), obj.get("device_id")),
        "station_name": _first_present(station_obj.get("name"), station_obj.get("stationName"), station_obj.get("station_name"), obj.get("stationName"), obj.get("station_name")),
        "station_town_center": _first_present(station_obj.get("townCenter"), station_obj.get("town_centre"), station_obj.get("town_center"), obj.get("townCenter"), obj.get("town_center")),
        "station_lat": lat,
        "station_lon": lon,
    }


def _records_from_v2_reading(reading: dict[str, Any]) -> list[dict[str, Any]]:
    """Return station records from a v2 `reading` entry across schema variants."""
    item = reading.get("item") if isinstance(reading.get("item"), dict) else None
    candidates = [
        reading.get("data"),
        reading.get("readings"),
        reading.get("records"),
        reading.get("values"),
        reading.get("stations"),
        item.get("readings") if item else None,
        item.get("records") if item else None,
        item.get("values") if item else None,
    ]
    for records in candidates:
        if records is None:
            continue
        if isinstance(records, list):
            return [x for x in records if isinstance(x, dict)]
        if isinstance(records, dict):
            for key in ["stations", "readings", "records", "values", "data"]:
                inner = records.get(key)
                if isinstance(inner, list):
                    return [x for x in inner if isinstance(x, dict)]
    # Some endpoints may put value/station fields directly on the reading item.
    if any(k in reading for k in ["value", "wbgt", "stationId", "station_id", "station"]):
        return [reading]
    return []


def _value_from_record(rec: dict[str, Any]) -> Any:
    """Extract a measurement value from common realtime weather record keys."""
    for key in ["value", "wbgt", "temperature", "relativeHumidity", "windSpeed", "reading", "measurement"]:
        if key in rec:
            return rec.get(key)
    if isinstance(rec.get("data"), dict):
        return _value_from_record(rec["data"])
    return None


def _station_lookup_from_v1(payload: Dict[str, Any]):
    meta = payload.get("metadata", {}) or {}
    stations: dict[str, dict[str, Any]] = {}
    for s in meta.get("stations", []) or []:
        sid = s.get("id") or s.get("station_id") or s.get("stationId")
        loc = s.get("location", {}) or {}
        if sid is not None:
            stations[str(sid)] = {
                "station_id": str(sid),
                "device_id": s.get("device_id") or s.get("deviceId"),
                "station_name": s.get("name"),
                "station_lat": loc.get("latitude"),
                "station_lon": loc.get("longitude"),
            }
    return stations, meta.get("reading_type") or meta.get("readingType"), meta.get("reading_unit") or meta.get("readingUnit")


def _station_lookup_from_v2(payload: Dict[str, Any]):
    data = payload.get("data", payload) or {}
    stations: dict[str, dict[str, Any]] = {}

    station_lists = []
    for obj in [payload, data, data.get("metadata", {}) if isinstance(data.get("metadata"), dict) else {}]:
        if isinstance(obj, dict) and isinstance(obj.get("stations"), list):
            station_lists.append(obj.get("stations") or [])
    for station_list in station_lists:
        for s in station_list:
            if not isinstance(s, dict):
                continue
            meta = _station_meta_from_any(s)
            sid = meta.get("station_id")
            if sid is not None:
                stations[str(sid)] = meta
    return stations, data.get("readingType") or data.get("reading_type"), data.get("readingUnit") or data.get("reading_unit")


def normalise_realtime_station_readings(payload: Dict[str, Any], value_name: str = "value") -> pd.DataFrame:
    """Normalise data.gov.sg realtime station responses to a flat table.

    Supports v1 `{metadata, items}` and v2 `{code, data}` shapes.
    """
    if not isinstance(payload, dict):
        raise TypeError("payload must be a dict")
    if payload.get("code", 0) not in (0, None):
        raise ValueError(f"data.gov.sg API error: {payload.get('errorMsg') or payload}")

    api_version = payload.get("_openheat_api_version") or ("v1" if "items" in payload else "v2")
    api_name = payload.get("_openheat_api_name")
    endpoint_url = payload.get("_openheat_endpoint_url")
    fetch_ts = payload.get("_openheat_fetch_timestamp_utc") or utc_now_iso()
    rows: list[dict[str, Any]] = []

    if "items" in payload:
        stations, reading_type, reading_unit = _station_lookup_from_v1(payload)
        for item in payload.get("items", []) or []:
            ts = item.get("timestamp") or item.get("update_timestamp") or item.get("time")
            for rec in item.get("readings", []) or []:
                sid = rec.get("station_id") or rec.get("stationId") or rec.get("id")
                sid = str(sid) if sid is not None else None
                rows.append({
                    "timestamp": ts,
                    **stations.get(sid, {"station_id": sid}),
                    value_name: rec.get("value"),
                    "reading_type": reading_type,
                    "reading_unit": reading_unit,
                    "api_name": api_name,
                    "api_version": api_version,
                    "endpoint_url": endpoint_url,
                    "fetch_timestamp_utc": fetch_ts,
                })
    else:
        data = payload.get("data", payload) or {}
        stations, reading_type, reading_unit = _station_lookup_from_v2(payload)

        # v2 APIs appear in two main shapes:
        # 1) older/generic: data.readings[]
        # 2) current WBGT/weather: data.records[].item.readings[] with record.datetime
        reading_containers: list[tuple[dict[str, Any], Any, Any]] = []
        if isinstance(data, dict) and isinstance(data.get("records"), list):
            for record in data.get("records", []) or []:
                if not isinstance(record, dict):
                    continue
                ts = _first_present(record.get("datetime"), record.get("timestamp"), record.get("time"), data.get("timestamp"), data.get("updateTime"))
                updated_ts = _first_present(record.get("updatedTimestamp"), record.get("updateTimestamp"), data.get("updatedTimestamp"), data.get("updateTime"))
                item = record.get("item") if isinstance(record.get("item"), dict) else record
                reading_containers.append((item, ts, updated_ts))
        else:
            readings = data.get("readings", []) if isinstance(data, dict) else []
            if isinstance(readings, dict):
                readings = [readings]
            for reading in readings or []:
                if not isinstance(reading, dict):
                    continue
                ts = reading.get("timestamp") or reading.get("time") or data.get("timestamp") or data.get("updateTime")
                updated_ts = reading.get("updatedTimestamp") or data.get("updatedTimestamp")
                reading_containers.append((reading, ts, updated_ts))

        for reading, ts, updated_ts in reading_containers:
            records = _records_from_v2_reading(reading)
            for rec in records:
                raw_sid = _first_present(rec.get("stationId"), rec.get("station_id"), rec.get("id"))
                embedded_meta = _station_meta_from_any(rec, fallback_id=str(raw_sid) if raw_sid is not None else None)
                sid = embedded_meta.get("station_id")
                station_meta = stations.get(sid, embedded_meta) if sid is not None else embedded_meta
                rows.append({
                    "timestamp": ts,
                    "record_updated_timestamp": updated_ts,
                    **station_meta,
                    value_name: _value_from_record(rec),
                    "heat_stress_category": _first_present(rec.get("heatStress"), rec.get("heat_stress"), rec.get("heatStressCategory")),
                    "reading_type": reading_type,
                    "reading_unit": reading_unit,
                    "api_name": api_name,
                    "api_version": api_version,
                    "endpoint_url": endpoint_url,
                    "fetch_timestamp_utc": fetch_ts,
                })

    df = pd.DataFrame(rows)
    # Guarantee metadata columns exist so downstream code can warn rather than crash.
    for c in ["station_id", "station_name", "station_town_center", "station_lat", "station_lon", "device_id"]:
        if c not in df.columns:
            df[c] = pd.NA
    if df.empty:
        return df
    df["timestamp"] = to_singapore_time_series(df["timestamp"])
    for c in [value_name, "station_lat", "station_lon"]:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
    df["value_missing"] = df[value_name].isna() if value_name in df.columns else True
    return df


def fetch_air_temperature(**kwargs) -> pd.DataFrame:
    return normalise_realtime_station_readings(fetch_datagov_realtime_api("air_temperature", **kwargs), "air_temperature_c")


def fetch_relative_humidity(**kwargs) -> pd.DataFrame:
    return normalise_realtime_station_readings(fetch_datagov_realtime_api("relative_humidity", **kwargs), "relative_humidity_percent")


def fetch_wind_speed(**kwargs) -> pd.DataFrame:
    df = normalise_realtime_station_readings(fetch_datagov_realtime_api("wind_speed", **kwargs), "wind_speed_raw")
    if not df.empty:
        unit = str(df["reading_unit"].dropna().iloc[0]).lower() if df["reading_unit"].notna().any() else ""
        df["wind_speed_ms"] = df["wind_speed_raw"] * 0.514444 if "knot" in unit else df["wind_speed_raw"]
    return df


def fetch_official_wbgt(**kwargs) -> pd.DataFrame:
    return normalise_realtime_station_readings(fetch_datagov_realtime_api("wbgt", **kwargs), "official_wbgt_c")


def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371000.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    return 2 * r * math.atan2(math.sqrt(a), math.sqrt(1 - a))


def attach_nearest_station(points_df: pd.DataFrame, stations_df: pd.DataFrame, *, point_lat="lat", point_lon="lon") -> pd.DataFrame:
    """Attach nearest station metadata and a representativeness flag."""
    if stations_df.empty:
        raise ValueError("stations_df is empty")
    st = stations_df.dropna(subset=["station_lat", "station_lon"]).drop_duplicates("station_id")
    if st.empty:
        raise ValueError("stations_df has no station coordinates")
    out_rows = []
    station_cols = [c for c in st.columns if c not in {"timestamp"}]
    for _, p in points_df.iterrows():
        distances = st.apply(lambda s: haversine_m(float(p[point_lat]), float(p[point_lon]), float(s["station_lat"]), float(s["station_lon"])), axis=1)
        idx = distances.idxmin()
        nearest = st.loc[idx, station_cols].to_dict()
        out = p.to_dict()
        out.update({f"nearest_{k}": v for k, v in nearest.items()})
        out["nearest_station_distance_m"] = float(distances.loc[idx])
        out["station_representativeness"] = (
            "local" if out["nearest_station_distance_m"] <= 1000 else
            "nearby_proxy" if out["nearest_station_distance_m"] <= 3000 else
            "regional_proxy"
        )
        out_rows.append(out)
    return pd.DataFrame(out_rows)


def merge_latest_station_observations(*dfs: pd.DataFrame) -> pd.DataFrame:
    """Merge latest available station observations by station_id."""
    cleaned = []
    for df in dfs:
        if df is None or df.empty or "station_id" not in df.columns:
            continue
        d = df.copy()
        if "timestamp" in d.columns:
            d = d.sort_values(["station_id", "timestamp"]).groupby("station_id", as_index=False).tail(1)
        else:
            d = d.drop_duplicates("station_id", keep="last")
        cleaned.append(d)
    if not cleaned:
        return pd.DataFrame()
    out = cleaned[0]
    for d in cleaned[1:]:
        shared_meta = [c for c in ["station_name", "station_lat", "station_lon", "device_id", "api_version", "endpoint_url"] if c in out.columns and c in d.columns]
        d2 = d.drop(columns=shared_meta, errors="ignore")
        out = out.merge(d2, on="station_id", how="outer", suffixes=("", "_rhs"))
    for c in list(out.columns):
        if c.endswith("_rhs"):
            out.drop(columns=[c], inplace=True, errors="ignore")
    return out
