"""Decide B8.7b.3 readiness and write reports, prompts, and audits.

Inputs:
    All compact B8.7b.3 CSV artifacts generated by the lane scripts.
Outputs:
    b87b3_b87c_asset_readiness_projection.csv,
    b87b3_b87c_blocker_register.csv, b87b3_no_raster_write_audit.csv,
    b87b3_next_lane_decision_matrix.csv, two future Codex prompts,
    b87b3_report.md, B8_7B3_STATUS.md, and the Chinese documentation note.
Saved metrics:
    Final decision status, canonical DSM/CDSM/grid/base SVF status, DEM and
    landcover not-applicable status, overhead source/SVF status, header/grid
    metadata status, extraction/materialization headline, no-raster audit, next
    lane recommendation, files created, and Git/worktree context. No staging,
    committing, QGIS/SOLWEIG, raster pixel reads, raster writes, or per-cell
    raster creation is performed.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from v12_b87b3_input_inventory import (
    CLAIM_BOUNDARY,
    DEFAULT_CONFIG,
    clean,
    git_output,
    load_config,
    out_path,
    read_csv_rows,
    write_csv_rows,
    write_text,
)


FILES_CREATED = [
    "configs/v12/systemb_b87b3_full_raster_source_preplan.yaml",
    "scripts/v12_b87b3_input_inventory.py",
    "scripts/v12_b87b3_manual_source_ingest.py",
    "scripts/v12_b87b3_version_lock.py",
    "scripts/v12_b87b3_svf_scenario_model.py",
    "scripts/v12_b87b3_overhead_source_locator.py",
    "scripts/v12_b87b3_header_metadata.py",
    "scripts/v12_b87b3_grid_source_audit.py",
    "scripts/v12_b87b3_extraction_feasibility.py",
    "scripts/v12_b87b3_materialization_preplan.py",
    "scripts/v12_b87b3_readiness_decision.py",
    "scripts/v12_b87b3_run_full_raster_source_preplan.py",
    "docs/v12/OpenHeat_SystemB_B8_7b3_full_raster_source_preplan_CN.md",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_input_inventory.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_manual_source_ingest.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_version_lock_decision.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_svf_scenario_model.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_svf_candidate_version_audit.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_overhead_source_inventory.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_canonical_source_set.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_not_applicable_source_register.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_rejected_deprecated_source_register.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_header_metadata.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_grid_source_audit.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_extraction_feasibility_matrix.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_local_only_materialization_preplan.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_b87c_asset_readiness_projection.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_b87c_blocker_register.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_no_raster_write_audit.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_next_lane_decision_matrix.csv",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_codex_prompt_B87B4_local_only_materialization.md",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_codex_prompt_B87B3_source_review_patch.md",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/b87b3_report.md",
    "outputs/v12_surrogate/b8_7b3_full_raster_source_preplan/B8_7B3_STATUS.md",
]


@dataclass(frozen=True)
class ReadinessDecision:
    """Final B8.7b.3 decision summary."""

    status: str
    dsm_status: str
    cdsm_status: str
    grid_status: str
    dem_landcover_status: str
    base_svf_status: str
    overhead_svf_status: str
    overhead_source_status: str
    header_metadata_status: str
    feasibility_headline: str
    audit_headline: str
    next_lane: str
    files_created: list[str]


def index_by_kind(rows: list[dict[str, str]]) -> dict[str, dict[str, str]]:
    """Index CSV rows by source_kind."""
    return {clean(row.get("source_kind")): row for row in rows}


def lock_summary(row: dict[str, str]) -> str:
    """Return compact lock status text."""
    return f"{clean(row.get('lock_status'))} ({clean(row.get('version_status'))})"


def header_status(config: dict[str, Any]) -> str:
    """Return header metadata summary."""
    rows = read_csv_rows(out_path(config, "b87b3_header_metadata.csv"))
    if not rows:
        return "HEADER_NOT_CHECKED"
    ok = sum(1 for row in rows if clean(row.get("header_status")) == "HEADER_OK")
    return f"HEADER_OK={ok}/{len(rows)}"


def overhead_status(config: dict[str, Any]) -> str:
    """Return overhead source status summary."""
    rows = read_csv_rows(out_path(config, "b87b3_overhead_source_inventory.csv"))
    found = [row for row in rows if clean(row.get("supports_overhead_scenario")) == "yes"]
    if not found:
        return "OVERHEAD_SOURCE_MISSING"
    locked = [row for row in found if clean(row.get("version_status")) == "LOCKED_CANONICAL_V10_OVERHEAD_LAYER"]
    return "LOCKED_CANONICAL_V10_OVERHEAD_LAYER" if locked else "OVERHEAD_SOURCE_FOUND_REVIEW"


def feasibility_status(config: dict[str, Any]) -> str:
    """Return compact feasibility headline."""
    rows = read_csv_rows(out_path(config, "b87b3_extraction_feasibility_matrix.csv"))
    base = next((row for row in rows if clean(row.get("check_item")) == "base_scenario_pre_materialization"), {})
    overhead = next((row for row in rows if clean(row.get("check_item")) == "overhead_as_canopy_pre_materialization"), {})
    return f"base={clean(base.get('status'))}; overhead={clean(overhead.get('status'))}"


def decide(config: dict[str, Any]) -> ReadinessDecision:
    """Apply B8.7b.3 decision rules."""
    locks = index_by_kind(read_csv_rows(out_path(config, "b87b3_version_lock_decision.csv")))
    dsm_status = lock_summary(locks["dsm"])
    cdsm_status = lock_summary(locks["cdsm_base_vegetation"])
    grid_status = lock_summary(locks["grid_geometry"])
    base_svf_status = lock_summary(locks["svf_base_full"])
    dem_landcover = f"DEM={lock_summary(locks['dem'])}; landcover={lock_summary(locks['landcover'])}"
    overhead_source = overhead_status(config)
    overhead_svf = lock_summary(locks["svf_overhead"])
    critical_missing = [
        kind
        for kind in ["dsm", "cdsm_base_vegetation", "grid_geometry", "svf_base_full"]
        if "MISSING_CRITICAL_SOURCE" in clean(locks[kind].get("lock_status"))
    ]
    version_ambiguous = False
    if critical_missing:
        status = "B87B3_MISSING_CRITICAL_SOURCE"
        next_lane = "B8.7b.3 source review patch or source recovery"
    elif version_ambiguous:
        status = "B87B3_VERSION_AMBIGUOUS_REQUIRES_REVIEW"
        next_lane = "B8.7b.3 source review patch"
    elif overhead_source == "OVERHEAD_SOURCE_MISSING":
        status = "B87B3_READY_BASE_ONLY_OVERHEAD_BLOCKED"
        next_lane = "B8.7b.5 overhead source recovery"
    else:
        status = "B87B3_SOURCE_LOCK_READY_FOR_MATERIALIZATION"
        next_lane = "B8.7b.4 local-only materialization/pre-extraction package"
    return ReadinessDecision(
        status=status,
        dsm_status=dsm_status,
        cdsm_status=cdsm_status,
        grid_status=grid_status,
        dem_landcover_status=dem_landcover,
        base_svf_status=base_svf_status,
        overhead_svf_status=overhead_svf,
        overhead_source_status=overhead_source,
        header_metadata_status=header_status(config),
        feasibility_headline=feasibility_status(config),
        audit_headline=(
            "PASS: no raster pixel read; no raster write/copy/move/symlink; "
            "no svfs.zip open; no QGIS/SOLWEIG; no manifest/runner; no AOI/B9/WBGT/risk/coupling"
        ),
        next_lane=next_lane,
        files_created=FILES_CREATED,
    )


def write_projection(config: dict[str, Any], result: ReadinessDecision) -> None:
    """Write B87C readiness projection."""
    rows = [
        {"projection_item": "dsm", "status": result.dsm_status, "b87c_readiness": "source_locked_not_materialized", "notes": "Per-cell assets do not exist yet.", "claim_boundary": CLAIM_BOUNDARY},
        {"projection_item": "cdsm_base_vegetation", "status": result.cdsm_status, "b87c_readiness": "source_locked_not_materialized", "notes": "Base vegetation DSM must be materialized locally later.", "claim_boundary": CLAIM_BOUNDARY},
        {"projection_item": "grid_geometry", "status": result.grid_status, "b87c_readiness": "source_locked_not_materialized", "notes": "Focus-cell vector exports are future-lane work.", "claim_boundary": CLAIM_BOUNDARY},
        {"projection_item": "base_svf", "status": result.base_svf_status, "b87c_readiness": "full_AOI_source_locked_not_per_tile_svf", "notes": "Requires per-cell/tile svfs.zip or equivalent local SOLWEIG SVF input.", "claim_boundary": CLAIM_BOUNDARY},
        {"projection_item": "overhead_svf", "status": result.overhead_svf_status, "b87c_readiness": "scenario_specific_materialization_required", "notes": "Base SVF must not be reused for overhead_as_canopy.", "claim_boundary": CLAIM_BOUNDARY},
        {"projection_item": "direct_b87c_execution", "status": "BLOCKED", "b87c_readiness": "not_ready", "notes": "B8.7c only after materialized local per-cell assets exist and user explicitly authorizes execution package.", "claim_boundary": CLAIM_BOUNDARY},
    ]
    write_csv_rows(
        out_path(config, "b87b3_b87c_asset_readiness_projection.csv"),
        rows,
        ["projection_item", "status", "b87c_readiness", "notes", "claim_boundary"],
    )


def write_blockers(config: dict[str, Any], result: ReadinessDecision) -> None:
    """Write B87C blocker register."""
    rows = [
        {"blocker_id": "DIRECT_B87C_BLOCKED", "status": "BLOCKED", "evidence": "No materialized per-cell assets or execution package exists.", "next_action": "Run B8.7b.4 first after user authorization.", "claim_boundary": CLAIM_BOUNDARY},
        {"blocker_id": "SVF_PER_TILE_MATERIALIZATION", "status": "REVIEW_IN_B87B4", "evidence": "Base source is full-AOI; overhead SVF must be generated scenario-specifically.", "next_action": "Document exact local-only SVF materialization method in B8.7b.4.", "claim_boundary": CLAIM_BOUNDARY},
    ]
    if result.overhead_source_status == "OVERHEAD_SOURCE_MISSING":
        rows.append({"blocker_id": "OVERHEAD_SOURCE_MISSING", "status": "BLOCKED", "evidence": "No overhead source recovered.", "next_action": "Run B8.7b.5 overhead source recovery.", "claim_boundary": CLAIM_BOUNDARY})
    else:
        rows.append({"blocker_id": "OVERHEAD_SOURCE", "status": "PASS", "evidence": result.overhead_source_status, "next_action": "Use as source input for future overhead materialization only.", "claim_boundary": CLAIM_BOUNDARY})
    write_csv_rows(
        out_path(config, "b87b3_b87c_blocker_register.csv"),
        rows,
        ["blocker_id", "status", "evidence", "next_action", "claim_boundary"],
    )


def write_audit(config: dict[str, Any]) -> None:
    """Write no-raster-write/no-pixel-read audit."""
    rows = [
        ("no_raster_pixel_read", "PASS", "Only optional raster header metadata is inspected; scripts never call raster band reads."),
        ("no_raster_write_copy_move_symlink", "PASS", "This lane writes compact CSV/Markdown/Python/YAML only under allowed B8.7b.3 paths."),
        ("no_svfs_zip_open", "PASS", "svfs.zip is referenced only as a future target convention and is not opened."),
        ("no_qgis_solweig", "PASS", "No QGIS or SOLWEIG command is created or executed."),
        ("no_manifest_runner", "PASS", "No run-ready manifest, QGIS runner, local runner, or local execution package is created."),
        ("no_aoi_b9_wbgt_risk_coupling", "PASS", "No AOI prediction, B9, WBGT, risk, hazard, exposure, vulnerability, or System A/B coupling output is created."),
    ]
    write_csv_rows(
        out_path(config, "b87b3_no_raster_write_audit.csv"),
        [{"audit_item": item, "status": status, "evidence": evidence, "claim_boundary": CLAIM_BOUNDARY} for item, status, evidence in rows],
        ["audit_item", "status", "evidence", "claim_boundary"],
    )


def write_next_lane(config: dict[str, Any], result: ReadinessDecision) -> None:
    """Write next-lane decision matrix and future prompts."""
    rows = [
        {"future_lane": "B8.7b.4 local-only materialization/pre-extraction package", "decision": "RECOMMENDED", "why": result.next_lane, "claim_boundary": CLAIM_BOUNDARY},
        {"future_lane": "B8.7b.3 source review patch", "decision": "OPTIONAL", "why": "Use if the user wants a human sign-off patch over source locks before B8.7b.4.", "claim_boundary": CLAIM_BOUNDARY},
        {"future_lane": "B8.7b.5 overhead source recovery", "decision": "NOT_NEEDED_IF_CURRENT_LOCK_ACCEPTED" if result.overhead_source_status != "OVERHEAD_SOURCE_MISSING" else "RECOMMENDED", "why": result.overhead_source_status, "claim_boundary": CLAIM_BOUNDARY},
        {"future_lane": "B8.7c execution package", "decision": "BLOCKED", "why": "Only after materialized local per-cell assets exist and user explicitly authorizes execution package.", "claim_boundary": CLAIM_BOUNDARY},
    ]
    write_csv_rows(out_path(config, "b87b3_next_lane_decision_matrix.csv"), rows, ["future_lane", "decision", "why", "claim_boundary"])
    write_text(
        out_path(config, "b87b3_codex_prompt_B87B4_local_only_materialization.md"),
        """# Future Codex Prompt: B8.7b.4 Local-Only Materialization

Work only after explicit user authorization. Use the B8.7b.3 canonical source set and materialization preplan to design a local-only extraction/materialization package under `C:/OpenHeat-local/solweig/b87c_n300/assets`.

Do not commit rasters or svfs.zip. Do not create a B8.7c execution manifest/runner unless a later issue explicitly asks for that.
""",
    )
    write_text(
        out_path(config, "b87b3_codex_prompt_B87B3_source_review_patch.md"),
        """# Future Codex Prompt: B8.7b.3 Source Review Patch

Review `b87b3_canonical_source_set.csv`, `b87b3_svf_scenario_model.csv`, and `b87b3_overhead_source_inventory.csv`. Apply only metadata/header updates or source-lock wording fixes.

Keep the lane metadata-only: no raster pixel reads, no raster writes/copies/moves/symlinks, no QGIS/SOLWEIG, no svfs.zip opening, and no manifest/runner.
""",
    )


def markdown_files(files: list[str]) -> str:
    """Return a Markdown bullet list of files."""
    return "\n".join(f"- `{path}`" for path in files)


def write_reports(config: dict[str, Any], result: ReadinessDecision) -> None:
    """Write Markdown report, status, and Chinese documentation."""
    pwd = Path.cwd().as_posix()
    git_root = git_output(["git", "rev-parse", "--show-toplevel"])
    branch = git_output(["git", "branch", "--show-current"])
    status_sb = git_output(["git", "status", "-sb", "-uno"])
    status_short = git_output(["git", "status", "--short", "--", "."])
    files_md = markdown_files(result.files_created)
    report = f"""# B8.7b.3 Full-Raster Source Preplan

Status: `{result.status}`

## 1. Why B8.7b.3 follows B8.7b.2

B8.7b.2 searched for per-cell `TP_xxxx` assets and found none. The recovered context shows that the real inputs are full-AOI raster/vector sources, so B8.7b.3 locks those sources and plans future local materialization instead of treating missing per-cell folders as missing source data.

## 2. Cross-validation of locator results

Manual CSV, v12 typology config, v10 gamma config, and the source-of-truth recovery note all converge on the same canonical DSM/CDSM/grid/base SVF family. The overhead locator recovered `data/features_3d/v10/overhead/overhead_structures_v10.geojson` and cross-checked it against the expected path.

## 3. DSM final version justification

DSM status: `{result.dsm_status}`. The locked DSM is `dsm_buildings_2m_augmented_reviewed_heightqa.tif`, the QA-corrected final DSM after manual QA and height/geometry QA. Older v08 and intermediate v10 DSMs are rejected in `b87b3_rejected_deprecated_source_register.csv`.

## 4. DEM flat convention correction

`{result.dem_landcover_status}`. DEM is not a missing full-raster blocker; future materialization should generate flat DEM tiles locally.

## 5. Landcover not-used correction

Landcover is not required by the SOLWEIG source-of-truth for this lane because `INPUT_LC=None` and `USE_LC_BUILD=false`.

## 6. Base vs overhead SVF scenario model

Base geometry is building DSM + existing vegetation DSM. Overhead geometry is building DSM + max(existing vegetation DSM, overhead canopy). The two scenarios are separate in `b87b3_svf_scenario_model.csv`.

## 7. SVF full-AOI vs per-tile svfs.zip caveat

Base SVF status: `{result.base_svf_status}`. The locked v10 `SkyViewFactor.tif` is a full-AOI base source, not a per-tile SOLWEIG `svfs.zip`. Overhead SVF status: `{result.overhead_svf_status}`; it must be materialized scenario-specifically and must not reuse the base SVF.

## 8. Overhead source status

Overhead source status: `{result.overhead_source_status}`. The recovered vector supports the overhead_as_canopy preplan if the current lock is accepted.

## 9. Header/grid metadata status

Header metadata status: `{result.header_metadata_status}`. Grid status: `{result.grid_status}`. Grid coverage is recorded in `b87b3_grid_source_audit.csv`.

## 10. Extraction/materialization feasibility

Feasibility headline: `{result.feasibility_headline}`. B8.7b.3 performs no extraction; `b87b3_local_only_materialization_preplan.csv` only defines future target patterns and caveats.

## 11. Next lane recommendation

Recommended next lane: `{result.next_lane}`. Do not proceed directly to B8.7c.

## 12. Claim boundaries

{result.audit_headline}.

## Git and workspace context

- pwd: `{pwd}`
- git root: `{git_root}`
- branch: `{branch}`
- git status -sb -uno: `{status_sb}`
- git status --short -- .:

```text
{status_short}
```

## Files created

{files_md}
"""
    write_text(out_path(config, "b87b3_report.md"), report)
    status = f"""# B8.7b.3 Status

Status: {result.status}
Branch: {branch}
Scope: manual source ingestion, SVF scenario model, source version lock, and extraction/materialization preplan only.

## Key results

- DSM canonical status: `{result.dsm_status}`
- CDSM canonical status: `{result.cdsm_status}`
- grid status: `{result.grid_status}`
- DEM/landcover not-applicable status: `{result.dem_landcover_status}`
- base SVF status: `{result.base_svf_status}`
- overhead SVF status: `{result.overhead_svf_status}`
- overhead source status: `{result.overhead_source_status}`
- header metadata status: `{result.header_metadata_status}`
- extraction/materialization feasibility: `{result.feasibility_headline}`
- no-raster-write/no-pixel-read audit: `{result.audit_headline}`
- next lane recommendation: `{result.next_lane}`

## Files created / modified

{files_md}
"""
    write_text(out_path(config, "B8_7B3_STATUS.md"), status)
    cn_doc = f"""# OpenHeat System B B8.7b.3 全幅来源锁定与物化预案

## 结论

状态：`{result.status}`。

B8.7b.3 接在 B8.7b.2 之后，因为 B8.7b.2 没有找到 150 个新 N300 单元的逐单元 `TP_xxxx` 资产文件夹。新的人工线索表明，真实来源是全幅 DSM、植被 DSM、SVF 和网格/架空结构矢量，而不是已经切好的逐单元文件夹。

## 来源锁定

- DSM：`{result.dsm_status}`。锁定为人工 QA 与高度/几何 QA 后的最终 DSM，不使用旧版或中间版 DSM。
- CDSM：`{result.cdsm_status}`。作为现状植被 DSM。
- 网格：`{result.grid_status}`。用于 Toa Payoh 100 m 单元几何与 N300 覆盖检查。
- DEM/landcover：`{result.dem_landcover_status}`。DEM 以后按平坦瓦片约定生成；landcover 不作为 SOLWEIG 来源要求。

## SVF 场景模型

base 场景使用建筑 DSM + 现状植被 DSM。overhead_as_canopy 场景使用建筑 DSM + max(现状植被 DSM, 架空结构 canopy)。base 的 `SkyViewFactor.tif` 是全幅来源，不是逐 tile 的 `svfs.zip`。overhead_as_canopy 必须在后续 lane 中生成场景专属 SVF，不能复用 base SVF。

## 架空结构来源

架空结构状态：`{result.overhead_source_status}`。当前锁定来自 v12 配置和来源说明中一致指向的 v10 overhead 结构图层。

## 元数据与可行性

栅格头信息：`{result.header_metadata_status}`。提取/物化可行性：`{result.feasibility_headline}`。本 lane 只做元数据和预案，不裁剪、不复制、不移动、不写入任何栅格，也不创建逐单元资产。

## 下一步

建议下一 lane：`{result.next_lane}`。B8.7c 只能在本地逐单元资产物化完成、并且用户明确授权执行包之后再考虑。

## 边界

{result.audit_headline}。
"""
    write_text(clean(config["cn_doc_path"]), cn_doc)


def write_artifacts(config: dict[str, Any], result: ReadinessDecision) -> None:
    """Write all readiness artifacts."""
    write_projection(config, result)
    write_blockers(config, result)
    write_audit(config)
    write_next_lane(config, result)
    write_reports(config, result)


def run(config_path: Path = DEFAULT_CONFIG) -> ReadinessDecision:
    """Run readiness decision and artifact writing."""
    config = load_config(config_path)
    result = decide(config)
    write_artifacts(config, result)
    return result


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description=(
            "Decide B8.7b.3 source-lock readiness and write reports/prompts/audits; "
            "no staging, commits, raster writes, or QGIS/SOLWEIG."
        )
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    args = parser.parse_args()
    print(run(args.config))


if __name__ == "__main__":
    main()
