"""Build Markdown handoff documents for the OpenHeat 2026-05-28 devlog.

Inputs:
  - A JSON-compatible YAML config passed with ``--config``.
  - CSV matrices generated by ``v12_devlog_inventory.py`` and
    ``v12_devlog_summarize_lanes.py``.

Outputs:
  - ``OPENHEAT_DEVLOG_STATUS.md``
  - ``openheat_devlog_report.md``
  - ``docs/handoff/OpenHeat_SystemA_SystemB_FULL_DEVLOG_2026-05-28_CN.md``
  - ``docs/handoff/OpenHeat_NEW_CHAT_REENTRY_CONTEXT_2026-05-28_CN.md``
  - ``docs/handoff/OpenHeat_ACTIVE_DEV_BOARD_2026-05-28.md``
  - ``docs/roadmap/OpenHeat_Roadmap_Status_Update_2026-05-28_CN.md``

Saved metrics:
  - inventoried lane count, missing/unreadable artifact count, selected
    checkpoints, blocked gates, claim-boundary decisions, and future-action
    stop conditions.
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(
        description="Build Chinese handoff and roadmap Markdown docs from devlog CSV matrices."
    )
    parser.add_argument(
        "--config",
        required=True,
        type=Path,
        help="Path to JSON-compatible YAML config declaring inputs and outputs.",
    )
    return parser.parse_args()


def load_config(path: Path) -> dict[str, Any]:
    """Load a JSON-compatible YAML config."""

    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def resolve_path(path_value: str, base_dir: Path) -> Path:
    """Resolve a config path relative to the current worktree."""

    path = Path(path_value).expanduser()
    if path.is_absolute():
        return path
    return (base_dir / path).resolve()


def read_csv(path: Path) -> list[dict[str, str]]:
    """Read a CSV file as dictionaries."""

    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def git_value(args: list[str], cwd: Path) -> str:
    """Return a git command value or a stable fallback."""

    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return "git_unavailable"
    value = result.stdout.strip()
    if result.returncode != 0:
        return f"git_error:{result.stderr.strip()}"
    return value


def md_escape(value: Any) -> str:
    """Escape a value for a compact Markdown table."""

    text = str(value if value is not None else "")
    return text.replace("|", "\\|").replace("\n", "<br>")


def md_table(rows: list[dict[str, Any]], headers: list[str]) -> str:
    """Render a Markdown table."""

    if not rows:
        return "_无记录。_"
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(md_escape(row.get(header, "")) for header in headers) + " |")
    return "\n".join(lines)


def write_text(path: Path, text: str) -> None:
    """Write UTF-8 text, creating parent directories."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def compact_lane_rows(lanes: list[dict[str, Any]], system: str) -> list[dict[str, Any]]:
    """Return compact lane rows for a system."""

    rows: list[dict[str, Any]] = []
    for lane in lanes:
        if lane["system"] != system:
            continue
        rows.append(
            {
                "lane": lane["lane_id"],
                "status": lane["status"],
                "class": lane["classification"],
                "result": "; ".join(lane.get("quantitative_results", [])[:3]),
                "next": lane["next_action"],
            }
        )
    return rows


def lane_detail_sections(lanes: list[dict[str, Any]], system: str) -> str:
    """Render complete per-lane detail tables."""

    sections: list[str] = []
    for lane in lanes:
        if lane["system"] != system:
            continue
        rows = [
            {"field": "状态", "value": lane["status"]},
            {"field": "分类", "value": lane["classification"]},
            {"field": "分支", "value": lane.get("branch", "")},
            {"field": "目的", "value": lane["purpose"]},
            {"field": "记录命令", "value": "; ".join(lane.get("commands", []))},
            {"field": "配置", "value": "; ".join(lane.get("configs", []))},
            {"field": "脚本", "value": "; ".join(lane.get("scripts", []))},
            {"field": "文档", "value": "; ".join(lane.get("docs", []))},
            {"field": "输出目录", "value": lane["output_dir"]},
            {"field": "关键输出", "value": "; ".join(lane.get("key_outputs", []))},
            {"field": "关键发现", "value": "; ".join(lane.get("key_findings", []))},
            {"field": "量化结果", "value": "; ".join(lane.get("quantitative_results", []))},
            {"field": "接受结论", "value": lane["accepted_conclusion"]},
            {"field": "注意事项", "value": "; ".join(lane.get("caveats", []))},
            {"field": "禁止表述", "value": "; ".join(lane.get("forbidden_claims", []))},
            {"field": "下一步", "value": lane["next_action"]},
            {"field": "重入命令", "value": lane.get("reentry_command", "not_applicable")},
        ]
        sections.append(f"### {lane['lane_id']} {lane['name']}\n\n" + md_table(rows, ["field", "value"]))
    return "\n\n".join(sections)


def filter_rows(rows: list[dict[str, str]], **filters: str) -> list[dict[str, str]]:
    """Filter CSV rows by exact values."""

    filtered = rows
    for key, value in filters.items():
        filtered = [row for row in filtered if row.get(key) == value]
    return filtered


def path_list(config: dict[str, Any], keys: list[str]) -> str:
    """Render configured output paths as Markdown bullets."""

    outputs = config["outputs"]
    return "\n".join(f"- `{outputs[key]}`" for key in keys)


def build_main_doc(
    config: dict[str, Any],
    cwd: Path,
    status_rows: list[dict[str, str]],
    decision_rows: list[dict[str, str]],
    claim_rows: list[dict[str, str]],
    future_rows: list[dict[str, str]],
    missing_rows: list[dict[str, str]],
) -> str:
    """Build the full Chinese devlog handoff."""

    lanes = config["lanes"]
    git_root = git_value(["rev-parse", "--show-toplevel"], cwd)
    branch = git_value(["branch", "--show-current"], cwd)
    status_sb = git_value(["status", "-sb", "-uno"], cwd)
    short_status = git_value(["status", "--short", "--", "."], cwd)
    missing_count = len(missing_rows)

    system_a_table = md_table(compact_lane_rows(lanes, "System A"), ["lane", "status", "class", "result", "next"])
    system_b_table = md_table(compact_lane_rows(lanes, "System B"), ["lane", "status", "class", "result", "next"])

    return f"""# OpenHeat System A + System B 全量开发日志与新聊天交接

生成日期：`{config['metadata']['current_date']}`  
当前 lane：`{config['metadata']['lane_name']}`  
项目身份：{config['metadata']['project_identity']}

## 1. 顶层摘要

| 项目 | 当前值 |
| --- | --- |
| 主工作区 | `{cwd}` |
| git root | `{git_root}` |
| 当前分支 | `{branch}` |
| git status -sb -uno | `{status_sb}` |
| 当前工作区短状态 | `{short_status if short_status else 'clean for tracked files; see untracked devlog/B87G0 files as applicable'}` |
| 缺失或不可读证据数 | `{missing_count}` |

核心边界：本项目当前仍是 WBGT-gated、SOLWEIG-informed、surrogate-assisted 的 Toa Payoh 本地热危害排序原型。本文不把任何输出升级为本地 100m WBGT、官方预警概率、AOI/B9 推理、风险图、观测真值或 System A/B 已耦合产品。System A 与 System B 是不同层。

## 2. 架构对齐

```mermaid
flowchart LR
  A["System A: hourly WBGT_A temporal severity"] --> C["Future Product C: WBGT-conditioned radiative priority"]
  A2["System A Level 2: station residual explanatory sidecar"] -. "no correction output" .-> A
  B["System B: SOLWEIG-derived Tmrt spatial radiative layer"] --> C
  C -. "future only" .-> R["Risk = hazard x exposure x vulnerability"]
```

| 层 | 当前解释 | 禁止升级 |
| --- | --- | --- |
| System A Level 1 | `wbgt_a_c` 是冻结主输出；P_ge31、期望超阈值、区间是可选诊断伴随列 | 本地 100m WBGT、官方预警概率 |
| System A Level 2 | 站点残差解释性侧车，弱高尾信号，score residual 不可识别 | station-adjusted WBGT、因果修正 |
| System B | SOLWEIG 模拟 Tmrt / `delta_tmrt_p90_c` 空间辐射层和 surrogate 检查点 | Tmrt=WBGT、AOI/B9、风险图 |
| Product C | 未来 WBGT-conditioned radiative priority | 当前不得声称已耦合 |
| Risk | 未来 hazard x exposure x vulnerability | 当前未开始 |

## 3. System A 总览

最终解释：Level 1 deterministic `wbgt_a_c` 是冻结主输出；`p_ge31_optional`、expected exceedance、conformal/interval diagnostics 只能作为可选诊断伴随列；`p_ge33_optional` 仍是探索性。A-L1H.6 等正式快照；A-L1H.7 等真实正式输入；A-L1H.8 dossier pass / frozen handoff。Level 2 仅解释性侧车。

{system_a_table}

{lane_detail_sections(lanes, "System A")}

## 4. System B 总览

最终解释：B87C full_150 raw SOLWEIG 已完成；B87D N300 label integration pass；B87E benchmark pass/no promotion；B87F 保留 extra_trees 候选但不放行 AOI；B87F2 是当前最佳本地源 surrogate checkpoint；B87G0 证明本地 proxy/source breakthrough 已耗尽，继续必须依赖外部 true-vector source acquisition 或关闭本阶段。

{system_b_table}

{lane_detail_sections(lanes, "System B")}

## 5. 关键决策登记

{md_table(decision_rows, ['decision_id', 'system', 'decision', 'status', 'evidence', 'accepted_interpretation', 'forbidden_interpretation'])}

## 6. Claim Boundary Matrix

{md_table(claim_rows, ['claim', 'decision', 'allowed_wording', 'forbidden_upgrade', 'rationale'])}

## 7. Future Action Matrix

{md_table(future_rows, ['action_id', 'allowed_next_action', 'prerequisites', 'command_or_prompt_path', 'expected_benefit', 'risk', 'stop_condition', 'forbidden_action'])}

## 8. 缺失或不可读证据

{md_table(missing_rows, ['artifact_id', 'group', 'relative_path', 'missing_reason'])}

## 9. 重入顺序

1. 先读本文件。
2. 再读 `docs/handoff/OpenHeat_NEW_CHAT_REENTRY_CONTEXT_2026-05-28_CN.md`。
3. System A 继续前先读 AL1H sibling 中的 A-L1H.8 dossier 和 A-L1H.5 output contract。
4. System B 继续前先读 B87G0 status/report、B87F2 report、B87D label QA。
5. 只有在真实外部 true-vector source 或真实 System A formal snapshot 存在时，才打开后续 lane。
"""


def build_report_doc(
    config: dict[str, Any],
    status_rows: list[dict[str, str]],
    artifact_rows: list[dict[str, str]],
    missing_rows: list[dict[str, str]],
) -> str:
    """Build compact output report."""

    created = path_list(
        config,
        [
            "input_inventory_csv",
            "file_inventory_csv",
            "lane_timeline_csv",
            "status_matrix_csv",
            "artifact_matrix_csv",
            "decision_register_csv",
            "claim_boundary_csv",
            "future_action_csv",
            "missing_artifacts_csv",
            "status_md",
            "report_md",
            "full_devlog_doc",
            "new_chat_context_doc",
            "active_dev_board_doc",
            "roadmap_update_doc",
        ],
    )
    return f"""# OPENHEAT_DEVLOG_2026_05_28 报告

## 状态

`PASS_CREATED_DEVLOG_HANDOFF`

Alias: `PASS_CREATED_SYNTHESIS_ARTIFACTS` was used in an earlier compact report draft for the same successful synthesis-artifact creation state.

## 生成文件

{created}

## 统计

| metric | value |
| --- | --- |
| inventoried_lanes | {len(status_rows)} |
| lane_artifact_rows | {len(artifact_rows)} |
| missing_or_unreadable_artifacts | {len(missing_rows)} |

## 结论

System A 冻结等待正式快照；System B 停在 B87G0 external-source-required gate。本文只做文档、inventory、handoff，不创建 AOI/B9/WBGT/risk 输出。
"""


def build_status_doc(
    config: dict[str, Any],
    status_rows: list[dict[str, str]],
    missing_rows: list[dict[str, str]],
) -> str:
    """Build status Markdown."""

    system_a = filter_rows(status_rows, system="System A")
    system_b = filter_rows(status_rows, system="System B")
    return f"""# OPENHEAT DEVLOG STATUS

Status: `PASS_CREATED_DEVLOG_HANDOFF`

| item | value |
| --- | --- |
| date | `{config['metadata']['current_date']}` |
| System A current state | Frozen/waiting; `wbgt_a_c` primary; optional diagnostics only |
| System B current state | B87G0 external-source-required; AOI/B9 blocked |
| best System B checkpoint | B87F2 local-source surrogate checkpoint |
| inventoried System A lanes | {len(system_a)} |
| inventoried System B lanes | {len(system_b)} |
| missing/unreadable artifacts | {len(missing_rows)} |

No QGIS, SOLWEIG, ML benchmarks, raster processing, AOI prediction, B9, WBGT conversion, hazard/risk/exposure/vulnerability outputs, staging, or commit were performed by this devlog lane.
"""


def build_new_chat_context(config: dict[str, Any]) -> str:
    """Build paste-ready new-chat context."""

    read_first = "\n".join(f"- `{item}`" for item in config["new_chat_read_first"])
    b8_commands = "\n".join(config.get("new_chat_b8_commands", config["new_chat_commands"]))
    al1h_commands = "\n".join(config.get("new_chat_al1h_commands", []))
    return f"""# OpenHeat 新聊天重入上下文（2026-05-28）

项目身份：{config['metadata']['project_identity']}

主 worktree：`{config['metadata']['primary_worktree']}`  
可读 sibling：`{config['metadata']['main_sibling']}`；`{config['metadata']['systema_sibling']}`

## 当前最佳状态

- System A：冻结等待。`wbgt_a_c` 是唯一主输出；P_ge31/expected exceedance/interval 是可选诊断；P_ge33 探索性；A-L1H.6/7 等真实 formal snapshot。
- System B：B87C raw SOLWEIG full_150 完成，B87D N300 label pass，B87E/F no promotion，B87F2 是最佳本地源 checkpoint，B87G0 结论是 external-source-required。
- 当前 stop/go：停止模型调参；只允许 external true-vector source acquisition 或关闭 System B surrogate phase。AOI/B9/WBGT/risk 全部 blocked。

## 先读文件

{read_first}

## 推荐下一 lane

1. System A：只有真实 formal snapshot 已存在时，先运行 A-L1H.7 freeze，再运行 A-L1H.6 prospective eval。
2. System B：只有外部 connected shade corridor / true tree-building source 可用时，开 external true-vector acquisition；否则写 closure note。
3. Product C/Risk：必须等 System A formal snapshot pass + System B AOI preflight source gates clear；risk 还需 exposure/vulnerability。

## 禁止表述

- 不说 local 100m WBGT。
- 不说 official warning probability。
- 不说 observed truth。
- 不说 AOI/B9 inference 已完成。
- 不说 hazard/risk/exposure/vulnerability output。
- 不说 SOLWEIG Tmrt 等于 WBGT。

## 重入命令

当前 PowerShell 中 bare `python` 不在 PATH；本轮验证使用 `C:/Users/CloudStar/anaconda3/envs/openheat/python.exe`。

### B8 / devlog / System B worktree

```powershell
{b8_commands}
```

### AL1H / System A reactivation worktree

```powershell
{al1h_commands}
```
"""


def build_active_board(config: dict[str, Any]) -> str:
    """Build active development board."""

    forbidden = "\n".join(f"- `{item}`" for item in config["forbidden_files"])
    approval = "\n".join(f"- {item}" for item in config["explicit_approval_only"])
    return f"""# OpenHeat Active Development Board - 2026-05-28

## Latest Stable Checkpoints

- System A: `A_L1H8_DOSSIER_PASS`, frozen/waiting, `wbgt_a_c` primary.
- System B: `B87G0_EXTERNAL_SOURCE_REQUIRED`; best local-source checkpoint remains `B87F2_FEATURE_PATCH_PARTIAL_NO_AOI`.
- B87C raw SOLWEIG: `3000/3000` success, 150 cells, 2 forcing days, 5 hours, 2 scenarios, 0 missing/empty Tmrt.
- B87D labels: 3000 N300 pairwise rows, 300 cells, 0 old/new overlap.

## Active / Paused Lanes

| lane | state | next |
| --- | --- | --- |
| System A formal snapshot | paused | wait for real compact formal snapshot |
| System A prospective eval | paused | run only after A-L1H.7 frozen snapshot |
| System B surrogate | blocked | external true-vector source acquisition or close phase |
| AOI/B9 | blocked | source gates plus explicit approval required |
| Product C coupling | deferred | needs System A formal pass and System B AOI preflight |
| Risk | deferred | needs explicit exposure/vulnerability layer |

## Recommended Next Lane

`System B external true-vector acquisition or closure note`; for System A, `formal snapshot reactivation` only if a real reviewed snapshot exists.

## Branches If Known

- Primary current branch at devlog start: `codex/b87g0-source-breakthrough-attempt`.
- System A evidence sibling branch: `codex/systema-development-dossier`.

## Forbidden Files

{forbidden}

## Claim Boundaries

- System A = calibrated hourly WBGT_A temporal baseline.
- System B = SOLWEIG-derived Tmrt/radiative spatial layer.
- Product C = future WBGT-conditioned radiative priority.
- Risk = future hazard x exposure x vulnerability, not started.

## Do Not Run Now

- QGIS, SOLWEIG, expensive raster processing, AOI prediction, B9, ML benchmark reruns, WBGT conversion, hazard/risk/exposure/vulnerability output.

## Run Only After Explicit Approval

{approval}
"""


def build_roadmap_update(config: dict[str, Any]) -> str:
    """Build roadmap status update."""

    rows = config["roadmap_update_rows"]
    return f"""# OpenHeat Roadmap Status Update - 2026-05-28

## 对比口径

- 2026-05-26 roadmap：在 sibling main 找到 `docs/roadmap/OpenHeat_Next_Development_Roadmap_2026-05-26_CN.md`；其状态仍停在 B8 surrogate / A-L1H 可并行启动的早期设想。
- 2026-05-27 framework：本轮复查在 B8 worktree 找到 `C:/Users/CloudStar/Documents/GitHub/Urban-Analytics-Portfolio/06-openheat_grid_b8/06-openheat_grid/docs/handoff/OpenHeat_NewDevRoadmap_Framework_2026-05-27_CN.md`。This framework exists as a conversation-uploaded planning artifact and should be copied into docs/handoff if repo completeness is desired.
- 2026-05-28 actual：以本 devlog inventory、System A AL1H sibling dossier、System B B87G0 worktree outputs 为准。

## 状态更新矩阵

{md_table(rows, ['topic', 'roadmap_2026_05_26', 'framework_2026_05_27', 'actual_2026_05_28', 'status', 'note'])}

## 重要修正

- System A Level 1 不再只是 pending probability companion：它已有冻结 output contract、optional P_ge31 diagnostic companion、prospective harness、snapshot freezer 和 dossier。
- System B 已远超 N24/N150 早期阶段：已有 N300 labels、benchmark、promotion review、true-vector/proxy patch 和 source-gate closeout。
- AOI/B9/risk 仍 blocked。
- System B 唯一继续路径是 external true-vector acquisition；否则关闭本阶段。
"""


def main() -> None:
    """CLI entrypoint."""

    args = parse_args()
    cwd = Path.cwd()
    config = load_config(args.config)
    outputs = config["outputs"]

    status_rows = read_csv(resolve_path(outputs["status_matrix_csv"], cwd))
    artifact_rows = read_csv(resolve_path(outputs["artifact_matrix_csv"], cwd))
    decision_rows = read_csv(resolve_path(outputs["decision_register_csv"], cwd))
    claim_rows = read_csv(resolve_path(outputs["claim_boundary_csv"], cwd))
    future_rows = read_csv(resolve_path(outputs["future_action_csv"], cwd))
    missing_rows = read_csv(resolve_path(outputs["missing_artifacts_csv"], cwd))

    write_text(
        resolve_path(outputs["status_md"], cwd),
        build_status_doc(config, status_rows, missing_rows),
    )
    write_text(
        resolve_path(outputs["report_md"], cwd),
        build_report_doc(config, status_rows, artifact_rows, missing_rows),
    )
    write_text(
        resolve_path(outputs["full_devlog_doc"], cwd),
        build_main_doc(config, cwd, status_rows, decision_rows, claim_rows, future_rows, missing_rows),
    )
    write_text(
        resolve_path(outputs["new_chat_context_doc"], cwd),
        build_new_chat_context(config),
    )
    write_text(
        resolve_path(outputs["active_dev_board_doc"], cwd),
        build_active_board(config),
    )
    write_text(
        resolve_path(outputs["roadmap_update_doc"], cwd),
        build_roadmap_update(config),
    )
    print(f"handoff_complete docs=6 missing={len(missing_rows)}")


if __name__ == "__main__":
    main()
