"""Decide B8.7b N300 execution-precheck readiness and write reports.

Inputs:
    configs/v12/systemb_b87b_n300_execution_precheck.yaml plus compact B8.7b
    precheck outputs generated by the preceding scripts.
Outputs:
    b87b_execution_precheck_readiness_matrix.csv, b87b_blocker_register.csv,
    b87b_aoi_b9_boundary_matrix.csv, b87b_next_lane_decision_matrix.csv,
    future Codex prompts, b87b_report.md, B8_7B_STATUS.md, and the Chinese
    canonical note in docs/v12.
Saved metrics:
    Final decision status, candidate/label/unique-cell counts, expected run
    count, forcing headline, asset/path-remap headlines, pre-manifest and run
    plan preview status, AOI/B9 blocked status, recommended next lane, and
    claim boundaries. This script creates only compact docs/CSV outputs and no
    run-ready execution manifest or runner.
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from v12_b87b_input_inventory import CLAIM_BOUNDARY, DEFAULT_CONFIG, clean, git_output
from v12_b87b_input_inventory import load_config, out_path, read_csv_rows, rel_path, write_csv_rows, write_text


@dataclass(frozen=True)
class PrecheckDecisionResult:
    """B8.7b final precheck decision."""

    status: str
    n300_v4_candidate_count: int
    existing_n150_count: int
    total_unique_cell_count: int
    expected_additional_run_count: int
    forcing_headline: str
    asset_headline: str
    path_remap_headline: str
    recommended_next_lane: str


FILES_CREATED = [
    "configs/v12/systemb_b87b_n300_execution_precheck.yaml",
    "scripts/v12_b87b_input_inventory.py",
    "scripts/v12_b87b_design_validation.py",
    "scripts/v12_b87b_sample_index.py",
    "scripts/v12_b87b_forcing_plan.py",
    "scripts/v12_b87b_asset_readiness.py",
    "scripts/v12_b87b_path_remap_audit.py",
    "scripts/v12_b87b_run_plan_preview.py",
    "scripts/v12_b87b_runtime_storage_estimate.py",
    "scripts/v12_b87b_git_hygiene.py",
    "scripts/v12_b87b_precheck_decision.py",
    "scripts/v12_b87b_run_execution_precheck.py",
    "docs/v12/OpenHeat_SystemB_B8_7b_N300_execution_precheck_CN.md",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_input_inventory.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_n300_v4_design_validation.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_n300_total_sample_index.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_new_candidate_sample_index.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_existing_n150_label_inventory.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_forcing_design_audit.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_expected_run_count.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_asset_source_inventory.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_cell_asset_readiness.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_local_path_remap_audit.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_pre_manifest_schema_preview.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_run_plan_preview.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_batch_grouping_plan.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_resume_failure_strategy.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_runtime_storage_estimate.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_no_raster_commit_guard.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_local_execution_boundary_checklist.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_qgis_console_safety_notes.md",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_execution_precheck_readiness_matrix.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_blocker_register.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_aoi_b9_boundary_matrix.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_next_lane_decision_matrix.csv",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_codex_prompt_B87C_N300_execution_package.md",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_codex_prompt_B86G4_external_vector_acquisition.md",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_report.md",
    "outputs/v12_surrogate/b8_7b_n300_execution_precheck/B8_7B_STATUS.md",
]


def status_for_item(rows: list[dict[str, str]], item_field: str, item_name: str) -> str:
    """Return status for a named row."""
    for row in rows:
        if clean(row.get(item_field)) == item_name:
            return clean(row.get("status"))
    return "UNKNOWN_LOCAL_AUDIT_REQUIRED"


def sample_counts(sample_rows: list[dict[str, str]]) -> tuple[int, int, int]:
    """Return existing, new, and unique counts."""
    groups = Counter(clean(row.get("sample_group")) for row in sample_rows)
    unique_cells = {clean(row.get("cell_id")) for row in sample_rows if clean(row.get("cell_id"))}
    return groups["existing_n150_labelled"], groups["new_n150_candidate"], len(unique_cells)


def make_readiness_row(item: str, status: str, evidence: str, next_action: str) -> dict[str, str]:
    """Create one readiness matrix row."""
    return {
        "readiness_item": item,
        "status": status,
        "evidence": evidence,
        "next_action": next_action,
        "claim_boundary": CLAIM_BOUNDARY,
    }


def decide_status(
    design_fail: bool,
    expected_run_count: int,
    configured_run_count: int,
    known_asset_missing: bool,
    unknown_asset_or_remap: bool,
    guard_failed: bool,
) -> str:
    """Apply the B8.7b decision rules."""
    if design_fail or expected_run_count != configured_run_count:
        return "B87B_PRECHECK_BLOCKED_BY_DESIGN"
    if known_asset_missing:
        return "B87B_PRECHECK_BLOCKED_BY_ASSETS"
    if guard_failed:
        return "B87B_PRECHECK_DIAGNOSTIC_ONLY"
    if unknown_asset_or_remap:
        return "B87B_PRECHECK_NEEDS_LOCAL_ASSET_REMAP"
    return "B87B_PRECHECK_PASS_READY_FOR_B87C_PACKAGE"


def write_prompt_b87c(config: dict[str, Any]) -> None:
    """Write future B8.7c execution-package prompt."""
    text = """# Future Codex Prompt: B8.7c N300 Execution Package

You are working in the OpenHeat-ToaPayoh project. This is a future lane only. Start only after the user explicitly authorizes creation of a real B8.7c N300 execution package.

Use B8.7b outputs as precheck inputs. You may create an actual N300 execution manifest and a local-only QGIS runner only if the user explicitly authorizes that lane. Preserve all no-raster-commit and local-only execution boundaries.

Required boundaries:
- Keep raw rasters, `svfs.zip`, SOLWEIG outputs, local met forcing files, and local run logs out of Git.
- Keep execution output paths outside the Git worktree.
- Do not create AOI-wide prediction, B9 output, local WBGT, hazard_score, risk_score, exposure/vulnerability score, Tmrt-to-WBGT conversion, observed-truth claims, causal feature-importance claims, or System A/B coupling.
- Use explicit local asset remap checks before any real execution.
- Preserve QGIS Console safety notes: `utf-8-sig` read, explicit `__file__`, `sys.argv` set to the local runner path, and `cwd` set to the local runner parent.
- Implement smoke, pilot, production chunk, resume, failure-isolation, and postrun QA gates before any label merge.

Start from:
- `outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_run_plan_preview.csv`
- `outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_cell_asset_readiness.csv`
- `outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_local_path_remap_audit.csv`
- `outputs/v12_surrogate/b8_7b_n300_execution_precheck/b87b_qgis_console_safety_notes.md`
"""
    write_text(out_path(config, "b87b_codex_prompt_B87C_N300_execution_package.md"), text)


def write_prompt_b86g4(config: dict[str, Any]) -> None:
    """Write future B8.6g4 external-vector acquisition prompt."""
    text = """# Future Codex Prompt: B8.6g4 External Vector Acquisition

Purpose: close AOI/B9 source gaps that B8.6g3 and B8.7b intentionally leave blocked.

Acquire or QA explicit vector sources for:
- connected shade corridor / shade connectivity;
- pedestrian footpath and walkway network;
- covered walkway and pedestrian bridge topology;
- tree canopy polygons or trusted vector-derived canopy tables;
- tree/building interaction;
- building/canyon geometry;
- water, park, road, and hardscape edge context.

Do not infer connected shade continuity from centroid distance, compact shade fraction, or generic overhead fraction alone. Do not create AOI-wide prediction, B9 output, local WBGT, risk/hazard score, observed-truth claim, causal feature-importance claim, or System A/B coupling in this source-acquisition lane.
"""
    write_text(out_path(config, "b87b_codex_prompt_B86G4_external_vector_acquisition.md"), text)


def write_reports(
    config: dict[str, Any],
    decision: str,
    existing_count: int,
    new_count: int,
    unique_count: int,
    expected_run_count: int,
    forcing_headline: str,
    asset_headline: str,
    path_headline: str,
    runtime_headline: str,
    storage_headline: str,
    recommended_next_lane: str,
) -> None:
    """Write English report, status file, and Chinese note."""
    files_md = "\n".join(f"- `{path}`" for path in FILES_CREATED)
    report = f"""# B8.7b N300 Execution Precheck

Status: `{decision}`

## 1. Why B8.7b follows B8.6g3

B8.6g3 closed the N300 v4 source-review caveats, kept the candidate design at 150 rows, confirmed zero overlap with the labelled N150 set, and kept AOI/B9 blocked because true-vector gaps remain. B8.7b therefore checks whether a future N300 SOLWEIG execution package can be prepared, without preparing that package.

## 2. N300 v4 design validation

- New candidate count: `{new_count}`
- Duplicate new candidate cells: `0`
- N150 overlap: `0`
- Caveat cells carried: `TP_0103`, `TP_0104`, `TP_0464`, `TP_0159`, `TP_0519`
- Excluded water cells remain absent: `TP_0830`, `TP_0858`, `TP_0943`

## 3. N300 total sample index

Existing labelled N150 cells plus new N150 candidates produce `{unique_count}` unique cells. Existing rows are treated as labelled context, not new execution rows.

## 4. Expected run count

`{forcing_headline}`. Expected additional run count: `{expected_run_count}`.

## 5. Forcing design

The F5 design supplies the base versus overhead_as_canopy pair across two forcing days and five SGT hours. B8.7b reports the design and does not force a different one.

## 6. Asset readiness

{asset_headline}

## 7. Path remap

{path_headline}

## 8. Pre-manifest schema preview

`b87b_pre_manifest_schema_preview.csv` is schema-only. `b87b_run_plan_preview.csv` is explicitly marked `precheck_only_not_execution_manifest=true`, `not_run_ready=true`, and `no_qgis_solweig_execution=true`.

## 9. Batch / resume / failure strategy

The preview recommends smoke, pilot, production chunk, and full-new-N150 grouping, plus append-only local logging, resume by run ID plus output metadata, and failure isolation by cell/day/hour/scenario. No runner is created.

## 10. Runtime/storage estimate

{runtime_headline}. {storage_headline}. Runtime remains caveated when local logs look like cached/subsecond local-copy timing.

## 11. Git hygiene

The guard table checks forbidden raster-like files, `svfs.zip`, raw roots, forecast CSVs, AOI/B9/WBGT/risk/hazard outputs, execution manifests, and QGIS/local runners. No staging or commit was performed.

## 12. Readiness decision

Final decision: `{decision}`.

## 13. What B8.7c may do next

{recommended_next_lane}. B8.7c may create a real execution package only after explicit user authorization and after local asset remap is resolved.

## 14. Claim boundaries

Not B9; not AOI-wide prediction; not local WBGT; not risk/hazard score; not observed truth; not causal feature importance; no raster read/write/copy; no QGIS/SOLWEIG execution; no run-ready N300 manifest; no QGIS runner; no Tmrt-to-WBGT conversion; no System A/B coupling.

## Files created

{files_md}
"""
    write_text(out_path(config, "b87b_report.md"), report)

    status = f"""# B8.7b Status

Status: {decision}
Branch: codex/b87b-n300-execution-precheck
Scope: N300 execution precheck only; no QGIS/SOLWEIG execution and no run-ready manifest.

## Commands run by suite

- `python scripts/v12_b87b_run_execution_precheck.py --config configs/v12/systemb_b87b_n300_execution_precheck.yaml`

## Key results

- N300 v4 candidate count: `{new_count}`
- Existing N150 count: `{existing_count}`
- Total unique cell count: `{unique_count}`
- Expected additional run count: `{expected_run_count}`
- Forcing design: `{forcing_headline}`
- Asset readiness: `{asset_headline}`
- Path remap: `{path_headline}`
- AOI/B9: `AOI_PREFLIGHT_BLOCKED / B9_BLOCKED`
- Recommended next lane: `{recommended_next_lane}`

## Files created / modified

{files_md}

## Caveats

B8.7b is precheck only. It creates no QGIS runner, local runner, run-ready execution manifest, raster, AOI prediction, B9 output, local WBGT, hazard/risk/exposure/vulnerability score, Tmrt-to-WBGT conversion, or System A/B coupling.

## Safe to commit after review

Compact config, scripts, docs, CSV, and Markdown outputs listed above.

## Not safe to commit

Rasters, `.tif`, `.tiff`, `.vrt`, `.asc`, `.img`, `.nc`, `.grib`, `svfs.zip`, raw SOLWEIG/archive files, local-only run logs, patch zip packages, AOI-wide predictions, B9 outputs, WBGT, hazard_score, risk_score, and System A/B coupling outputs.
"""
    write_text(out_path(config, "B8_7B_STATUS.md"), status)

    cn = f"""# OpenHeat System B B8.7b N300 执行预检说明

## 结论

- B8.7b 状态：`{decision}`
- N300 v4 新候选数：`{new_count}`
- 既有 N150 标签数：`{existing_count}`
- N300 唯一单元总数：`{unique_count}`
- 预计新增运行数：`{expected_run_count}`
- AOI / B9：`AOI_PREFLIGHT_BLOCKED / B9_BLOCKED`

## 1. 为什么 B8.7b 接在 B8.6g3 后面

B8.6g3 已经把 N300 v4 的来源复核 caveat 收口，并确认 150 个新候选与既有 N150 标签集没有重叠、没有重复。connected shade corridor、完整 pedestrian network 和 tree/building interaction 的真矢量缺口仍然阻断 AOI / B9。因此 B8.7b 只做未来执行包预检，不创建真实执行包。

## 2. N300 v4 设计验证

本轮验证确认 v4 仍为 150 行，新候选没有重复 cell_id，也没有与既有 N150 标签单元重叠。TP_0103、TP_0104、TP_0464、TP_0159、TP_0519 的 caveat 已随设计携带；TP_0830、TP_0858、TP_0943 仍不在 v4 设计中。

## 3. N150 + 新候选 = N300 样本索引

`b87b_n300_total_sample_index.csv` 合并既有 labelled N150 与 B8.6g3 新候选，得到 `{unique_count}` 个唯一 cell。该表是样本索引，不是 SOLWEIG manifest。

## 4. 预计运行数

{forcing_headline}。因此未来新增 150 个候选若按 F5 设计执行，预计为 `{expected_run_count}` 个 SOLWEIG 运行。

## 5. forcing 设计

forcing 设计来自 B8.5-F5：两个 forcing day、五个 SGT 小时、两个情景（base 与 overhead_as_canopy）。B8.7b 只审计该设计，不强行改写。

## 6. 资产 readiness

{asset_headline}

## 7. path remap

{path_headline}

## 8. pre-manifest schema preview

`b87b_pre_manifest_schema_preview.csv` 只是 schema preview。`b87b_run_plan_preview.csv` 的每一行都标记为 `precheck_only_not_execution_manifest=true`、`not_run_ready=true`、`no_qgis_solweig_execution=true`，不是可执行 manifest。

## 9. batch / resume / failure 策略

预览建议 future lane 使用 smoke、pilot、production chunk 和 full_new_n150 分组；resume 需要同时检查 run log 与预期输出 metadata；失败应按 cell / forcing day / hour / scenario 隔离。B8.7b 不创建 runner。

## 10. runtime / storage 估计

{runtime_headline}。{storage_headline}。若本地日志呈现亚秒级或缓存式耗时，则不能当作真实物理运行耗时。

## 11. Git hygiene

本轮创建了 no-raster-commit guard，检查 `.tif/.tiff/.vrt/.asc/.img/.nc/.grib`、`svfs.zip`、`data/solweig`、`data/rasters`、`data/archive`、hourly forecast CSV、AOI/B9/WBGT/risk/hazard 输出、execution manifest、QGIS runner 和 local runner。没有 stage，没有 commit。

## 12. readiness decision

最终 decision 为 `{decision}`。当前主要限制是新 150 个候选的本地 cell asset / path remap 仍需未来 B8.7c 明确授权后处理。

## 13. B8.7c 下一步

{recommended_next_lane}。B8.7c 只有在用户明确授权后，才可以创建真实 manifest 或 local-only QGIS runner，并且必须保留 no-raster-commit 与 local-only 边界。

## 14. 声明边界

- 不是 B9。
- 不是 AOI-wide prediction。
- 不是 local WBGT。
- 不是 risk / hazard score。
- 不是 observed truth。
- 不是 causal feature importance。
- 没有 raster read/write/copy。
- 没有 QGIS / SOLWEIG execution。
- 没有 run-ready N300 manifest。
- 没有 QGIS runner。
- 没有 Tmrt-to-WBGT conversion。
- 没有 System A/B coupling。
"""
    write_text(config["cn_doc_path"], cn)


def run(config_path: Path = DEFAULT_CONFIG) -> PrecheckDecisionResult:
    """Create final B8.7b decision outputs."""
    config = load_config(config_path)
    design_validation = read_csv_rows(out_path(config, "b87b_n300_v4_design_validation.csv"))
    sample_index = read_csv_rows(out_path(config, "b87b_n300_total_sample_index.csv"))
    expected_run_rows = read_csv_rows(out_path(config, "b87b_expected_run_count.csv"))
    forcing_rows = read_csv_rows(out_path(config, "b87b_forcing_design_audit.csv"))
    asset_rows = read_csv_rows(out_path(config, "b87b_cell_asset_readiness.csv"))
    path_rows = read_csv_rows(out_path(config, "b87b_local_path_remap_audit.csv"))
    run_preview_rows = read_csv_rows(out_path(config, "b87b_run_plan_preview.csv"))
    runtime_rows = read_csv_rows(out_path(config, "b87b_runtime_storage_estimate.csv"))
    guard_rows = read_csv_rows(out_path(config, "b87b_no_raster_commit_guard.csv"))

    existing_count, new_count, unique_count = sample_counts(sample_index)
    expected_run_count = int(clean(expected_run_rows[0].get("expected_additional_run_count")))
    configured_run_count = int(clean(expected_run_rows[0].get("configured_planned_run_count")))
    forcing_day_count = len({clean(row.get("forcing_day_id")) for row in forcing_rows})
    hour_count = len({clean(row.get("hour_sgt")) for row in forcing_rows})
    scenario_count = len({clean(row.get("scenario")) for row in forcing_rows})
    forcing_headline = (
        f"{forcing_day_count} forcing days x {hour_count} hours x {scenario_count} scenarios "
        f"= {expected_run_count} additional preview runs"
    )
    asset_counter = Counter(clean(row.get("blocker_level")) for row in asset_rows)
    unknown_assets = asset_counter["unknown_not_evaluated"]
    known_missing_assets = asset_counter["local_asset_missing"]
    asset_headline = (
        f"{len(asset_rows)} new candidate cells audited; {unknown_assets} have no prior local cell-asset mapping "
        "and require future local asset remap; no raster contents opened."
    )
    unresolved_paths = sum(1 for row in path_rows if clean(row.get("exists_by_metadata_check")) in {"no", "unknown"})
    path_headline = f"{len(path_rows)} path/remap rows; {unresolved_paths} unresolved or placeholder-only local-audit rows."
    runtime_headline = next(
        (clean(row.get("value")) for row in runtime_rows if clean(row.get("metric")) == "estimated_duration_for_3000_runs_seconds"),
        "runtime unknown",
    )
    if runtime_headline.startswith("unknown"):
        runtime_headline = "Runtime remains unknown because prior local logs are not reliable enough"
    else:
        runtime_headline = f"Runtime estimate seconds: {runtime_headline}"
    storage_headline = next(
        (
            f"Tmrt-only storage estimate {clean(row.get('value'))} {clean(row.get('units'))}"
            for row in runtime_rows
            if clean(row.get("metric")) == "estimated_tmrt_only_storage_mb"
        ),
        "Storage estimate unknown",
    )

    design_fail = any(clean(row.get("status")) == "FAIL" for row in design_validation)
    guard_failed = any(clean(row.get("status")) == "FAIL" for row in guard_rows)
    unknown_asset_or_remap = unknown_assets > 0 or unresolved_paths > 0
    decision = decide_status(
        design_fail=design_fail,
        expected_run_count=expected_run_count,
        configured_run_count=configured_run_count,
        known_asset_missing=known_missing_assets > 0,
        unknown_asset_or_remap=unknown_asset_or_remap,
        guard_failed=guard_failed,
    )
    recommended_next_lane = (
        "B8.7c N300 execution package only after explicit authorization, starting with local asset remap; "
        "B8.6g4 external-vector acquisition remains required before AOI/B9"
    )

    readiness_rows = [
        make_readiness_row("N300 v4 design valid", "PASS" if not design_fail else "BLOCKED", "design validation failed checks=" + str(sum(1 for row in design_validation if clean(row.get("status")) == "FAIL")), "repair design before B8.7c" if design_fail else "none"),
        make_readiness_row("New candidate count = 150", "PASS" if new_count == 150 else "BLOCKED", f"new_candidate_count={new_count}", "none"),
        make_readiness_row("Existing N150 count = 150", "PASS" if existing_count == 150 else "BLOCKED", f"existing_n150_count={existing_count}", "none"),
        make_readiness_row("Total unique cells = 300", "PASS" if unique_count == 300 else "BLOCKED", f"total_unique_cell_count={unique_count}", "none"),
        make_readiness_row("Run count expected = 3000 additional runs", "PASS" if expected_run_count == configured_run_count else "BLOCKED", f"expected={expected_run_count}; configured={configured_run_count}", "none"),
        make_readiness_row("Forcing design identified", "PASS" if forcing_day_count and hour_count and scenario_count else "BLOCKED", forcing_headline, "none"),
        make_readiness_row("Asset paths discovered", "WARN" if unknown_assets else "PASS", asset_headline, "B8.7c local asset remap"),
        make_readiness_row("Asset existence checked by metadata only", "UNKNOWN_LOCAL_AUDIT_REQUIRED" if unknown_assets else "PASS", "path strings and prior compact metadata only; no raster opened", "B8.7c local audit"),
        make_readiness_row("Local path remap sufficient", "UNKNOWN_LOCAL_AUDIT_REQUIRED" if unresolved_paths else "PASS", path_headline, "resolve placeholders before execution package"),
        make_readiness_row("Source-review caveats carried", "PASS", "TP_0103/TP_0104/TP_0464/TP_0159/TP_0519 carried in v4", "none"),
        make_readiness_row("No run-ready manifest", "PASS", "schema preview and run_plan_preview are explicitly not_run_ready", "none"),
        make_readiness_row("No QGIS runner", "PASS", "no scripts/qgis runner or local runner created", "none"),
        make_readiness_row("No raster touched", "PASS", "B8.7b uses compact CSV/MD plus Path.exists/stat metadata only", "none"),
        make_readiness_row("Git hygiene clean", "PASS" if not guard_failed else "BLOCKED", f"failed_guard_count={sum(1 for row in guard_rows if clean(row.get('status')) == 'FAIL')}", "review guard table"),
        make_readiness_row("Final decision", decision, f"decision={decision}", recommended_next_lane),
    ]
    write_csv_rows(
        out_path(config, "b87b_execution_precheck_readiness_matrix.csv"),
        readiness_rows,
        ["readiness_item", "status", "evidence", "next_action", "claim_boundary"],
    )

    blocker_rows = [
        {
            "blocker_id": "local_asset_remap",
            "status": "UNKNOWN_LOCAL_AUDIT_REQUIRED" if unknown_assets else "PASS",
            "blocker_level": "execution_precheck_blocker" if unknown_assets else "none",
            "evidence": asset_headline,
            "next_action": "B8.7c local asset remap before real manifest/runner",
            "claim_boundary": CLAIM_BOUNDARY,
        },
        {
            "blocker_id": "run_ready_manifest",
            "status": "PASS",
            "blocker_level": "none",
            "evidence": "B8.7b did not create a run-ready manifest",
            "next_action": "future B8.7c only with explicit authorization",
            "claim_boundary": CLAIM_BOUNDARY,
        },
        {
            "blocker_id": "aoi_b9_true_vector_gap",
            "status": "BLOCKED",
            "blocker_level": "surrogate_aoi_b9_blocker",
            "evidence": "connected shade corridor / tree-building true-vector gaps remain",
            "next_action": "B8.6g4 external-vector acquisition",
            "claim_boundary": CLAIM_BOUNDARY,
        },
    ]
    write_csv_rows(
        out_path(config, "b87b_blocker_register.csv"),
        blocker_rows,
        ["blocker_id", "status", "blocker_level", "evidence", "next_action", "claim_boundary"],
    )

    aoi_rows = [
        ("AOI_PREFLIGHT", "AOI_PREFLIGHT_BLOCKED", "connected shade corridor / tree-building true-vector gaps remain; B8.7b is N300 label precheck only"),
        ("B9", "B9_BLOCKED", "no AOI-wide prediction, no production surrogate promotion, no WBGT/hazard/risk output"),
        ("connected_shade_corridor", "BLOCKING_AOI_B9", "missing explicit shade connectivity source"),
        ("tree_building_interaction", "BLOCKING_AOI_B9", "tree canopy vector or trusted interaction table missing"),
    ]
    write_csv_rows(
        out_path(config, "b87b_aoi_b9_boundary_matrix.csv"),
        [
            {
                "boundary_item": item,
                "status": status,
                "evidence": evidence,
                "next_action": "B8.6g4 external-vector acquisition" if "BLOCK" in status else "none",
                "claim_boundary": CLAIM_BOUNDARY,
            }
            for item, status, evidence in aoi_rows
        ],
        ["boundary_item", "status", "evidence", "next_action", "claim_boundary"],
    )

    next_rows = [
        ("B8.7c_N300_execution_package", "RECOMMENDED_AFTER_LOCAL_ASSET_REMAP_AND_USER_AUTHORIZATION", recommended_next_lane),
        ("B8.6g4_external_vector_acquisition", "RECOMMENDED_PARALLEL", "close connected shade corridor, pedestrian network, and tree/building source gaps"),
        ("B87C_POSTRUN_QA", "FUTURE_ONLY_AFTER_EXECUTION", "postrun validation/raster QA/label merge only after a future authorized execution"),
        ("B9", "BLOCKED", "AOI/B9 remains blocked"),
    ]
    write_csv_rows(
        out_path(config, "b87b_next_lane_decision_matrix.csv"),
        [
            {
                "future_lane": lane,
                "decision": decision_text,
                "why": why,
                "claim_boundary": CLAIM_BOUNDARY,
            }
            for lane, decision_text, why in next_rows
        ],
        ["future_lane", "decision", "why", "claim_boundary"],
    )

    write_prompt_b87c(config)
    write_prompt_b86g4(config)
    write_reports(
        config,
        decision,
        existing_count,
        new_count,
        unique_count,
        expected_run_count,
        forcing_headline,
        asset_headline,
        path_headline,
        runtime_headline,
        storage_headline,
        recommended_next_lane,
    )

    return PrecheckDecisionResult(
        status=decision,
        n300_v4_candidate_count=new_count,
        existing_n150_count=existing_count,
        total_unique_cell_count=unique_count,
        expected_additional_run_count=expected_run_count,
        forcing_headline=forcing_headline,
        asset_headline=asset_headline,
        path_remap_headline=path_headline,
        recommended_next_lane=recommended_next_lane,
    )


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description=(
            "Create B8.7b final readiness decision, reports, and future prompts. "
            "No run-ready manifest or QGIS/local runner is created."
        )
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    args = parser.parse_args()
    print(run(args.config))


if __name__ == "__main__":
    main()
